name: Procesar CSV

on:
  push:
    paths:
      - 'procesamiento_resources/data/raw/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r procesamiento_resources/requirements.txt

      - name: Run script
        run: python procesamiento_resources/src/procesar_resources.py

      - name: Commit processed file
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add procesamiento_resources/data/processed/resources_processed.csv
          git commit -m "Auto update processed CSV"
          git push

      - name: Instalar dependencias
        run: |
          pip install pandas openpyxl
      - name: Ejecutar procesamiento evolution
        run: |
          python procesamiento_evolution/scripts/procesar_evolution.py
