name: Procesar Datos

on:
  push:
    paths:
      - 'procesamiento_resources/data/raw/**'
      - 'procesamiento_evolution/data/raw/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install pandas openpyxl

      # -------------------------
      # PROCESAR RESOURCES
      # -------------------------
      - name: Run resources processing
        run: |
          python procesamiento_resources/src/procesar_resources.py

      # -------------------------
      # PROCESAR EVOLUTION
      # -------------------------
      - name: Run evolution processing
        run: |
          python procesamiento_evolution/scripts/procesar_evolution.py

      # -------------------------
      # COMMIT SI HAY CAMBIOS
      # -------------------------
      - name: Commit processed files
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add procesamiento_resources/data/processed/resources_processed.csv
          git add procesamiento_evolution/data/processed/evolution_data_processed.csv

          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Auto update processed files"
            git push
          fi
